language: node_js
node_js:
  - 0.10
  - 0.11

before_script:
  - git lfs install
  - git lfs pull
  - ls -la test/fixtures/excessively-deep.tar || echo "File not found!"
  - file test/fixtures/excessively-deep.tar || echo "Cannot check file type"